### ISSUE TITLE
Not able to install quantum-grove in Windows 10

### ISSUE THREAD

**Issue by riyasett** [rigetticomputing/grove#101]
![issue 1](https://user-images.githubusercontent.com/33022941/32695099-2f044718-c753-11e7-9eb5-ffe237df51cd.png)
I am trying to install quantum-grove through Anaconda and also using "pip install -e <directory path>" after downloading the grove-master zip file. But there is error every time. I have attached the screenshot what it is saying every time. I have already installed pyquil-master using "pip install -e", no issue occurred at that time. 
![issue](https://user-images.githubusercontent.com/33022941/32695094-0a1b462c-c753-11e7-9b02-98c11a8d135f.png)

**Comment by jotterbach** [comment]
Thanks for reporting this @riyasett . We'll have a look and update you if we find out what happened.
@mpharrigan would you mind taking a stab at this?

**Comment by riyasett** [comment]
Hello,
Finally, it worked. I don't know how. I was just kept trying to install it in the same way and it is finally installed. Thank you all...

**Comment by jotterbach** [comment]
@riyasett Glad to hear it finally worked. I will close this ticket now. Feel free to re-open if you run into any new troubles
