### ISSUE TITLE
cannot calculate expectation from sample

### ISSUE THREAD

**Issue by huichencrytal** [rigetticomputing/grove#112]
> When I run the sample code on the VQE page
`vqe_inst.expectation(small_ansatz([angle]), hamiltonian, 10000, qvm)`

There is an error shown as below
![jietu20171205-171347](https://user-images.githubusercontent.com/34290205/33646275-8ce69788-da03-11e7-8cb1-496e2b0e1b2a.jpg)
![jietu20171205-171404](https://user-images.githubusercontent.com/34290205/33646277-8f406ff4-da03-11e7-8ff2-e24754bd5057.jpg)

**Comment by stevenheidel** [comment]
I just fixed this on PyQuil master. We will release a new version of PyQuil and Grove tomorrow. In the meantime you can use `pip install git+git://github.com/rigetticomputing/pyquil.git` to install the fixed version.
