### ISSUE TITLE
error happens when I add initial angles to the qaoa_maxcut 

### ISSUE THREAD

**Issue by huichencrytal** [rigetticomputing/grove#114]
The solution to the maxcut problem of ring is not unique，so I want to add an initial_beta and initial_gamma which I guess will give me the optimal angles near the given initial angles. Thus, I add initial angles to the qaoa_maxcut
`inst = maxcut_qaoa(graph=square_ring, steps=steps, initial_beta=1.2, initial_gamma=1.2 )`

> Then error happens as below

![jietu20171205-225939](https://user-images.githubusercontent.com/34290205/33649165-a014448c-da11-11e7-8ca4-ad4dbab56712.jpg)

![jietu20171205-230026](https://user-images.githubusercontent.com/34290205/33649172-a44272cc-da11-11e7-85cb-abe7f6b1227d.jpg)

**Comment by jotterbach** [comment]
@huichencrytal what's the number of `steps` you feed into your program? the number of initial values need to match two times the number of steps:
```import numpy as np
from grove.pyqaoa.maxcut_qaoa import maxcut_qaoa
import pyquil.api as qvm
qvm_connection = qvm.QVMConnection()

square_ring = [(0,1),(1,2),(2,3),(3,0)]
steps = 2
inst = maxcut_qaoa(graph=square_ring, steps=steps, initial_beta=[1.2, 0.3], initial_gamma=[0.4, -0.9])
betas, gammas = inst.get_angles()

t = np.hstack((betas, gammas))
param_prog = inst.get_parameterized_program()
prog = param_prog(t)
wf = qvm_connection.wavefunction(prog)
wf = wf.amplitudes```

This snippet works for me.

**Comment by huichencrytal** [comment]
@jotterbach Oh Yes! I forget to change the steps. It works now. I'm so sorry it seems like a stupid question.

**Comment by jotterbach** [comment]
@huichencrytal no problem at all! Glad this was it! A good way to get these things sorted out in a faster way is also the Forest Community slack channel http://slack.rigetti.com/

**Comment by huichencrytal** [comment]
@jotterbach Thank you very much! I just joined the Forest Community slack channel. Excited!
