### ISSUE TITLE
Error in phase estimation

### ISSUE THREAD

**Issue by Joshua-Gordon** [rigetticomputing/grove#165]
I ran the following script:

    import pyquil.api as api
    qvm = api.QVMConnection()

    import numpy as np
    from grove.alpha.phaseestimation.phase_estimation import phase_estimation
    precision = 18

    for p in range(10):
        phase = 1/(2**p)

        phase_factor = np.exp(1.0j * 2 * np.pi * phase)
        U = np.array([[phase_factor, 0],
                      [0, -1*phase_factor]])

        p = phase_estimation(U, precision)

        output = qvm.run(p, range(precision))
        wavefunction = qvm.wavefunction(p)

        print("~~~~~~~~~~~~~~~~~~~")
        print(phase)
        print(output)
        print(wavefunction)
        print("~~~~~~~~~~~~~~~~~~~")

For phase = 0.25, it outputs all zeros. After 0.125, it throws an error. Here is the output:
``~~~~~~~~~~~~~~~~~~~
1.0
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
(1+0j)|0000000000000000000>
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
0.5
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]
(1+0j)|0100000000000000000>
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
0.25
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
(1+0j)|0110000000000000000>
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
0.125
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]]
(1+0j)|0111000000000000000>
~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "C:\Users\Josh\Desktop\phaseTest.py", line 21, in <module>
    wavefunction = qvm.wavefunction(p)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36\lib\site-packages\pyquil\api\qvm.py", line 270, in wavefunction
    return Wavefunction.from_bit_packed_string(response.content, classical_addresses)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36\lib\site-packages\pyquil\wavefunction.py", line 93, in from_bit_packed_string
    return Wavefunction(wf, mem)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36\lib\site-packages\pyquil\wavefunction.py", line 41, in __init__
    "The probabilities sum to {} instead of 1".format(sumprob))
ValueError: The wavefunction is not normalized. The probabilities sum to 2.759271215133724e-32 instead of 1

**Comment by ntezak** [comment]
Hi @Joshua-Gordon can you print the versions of grove and pyquil that you are using? We fixed a related issue a while back...

**Comment by ntezak** [comment]
@Joshua-Gordon this should not happen if you are using the latest pyquil release and the current master branch of grove. We will be cutting a new release of grove very soon.
