### ISSUE TITLE
Recursive methods should be iterative

### ISSUE THREAD

**Issue by vontell** [rigetticomputing/grove#42]
While running some analytics on the Shor's algorithm implementation, I discovered that the QFT implementation crashes when working with large qubit ranges due to recursion depth limits. This may mean that we should go through our algorithms and look where recursion can be replaced by iterative processes, in order to avoid these kinds of bugs as we scale in the future.

**Comment by tarballs-are-good** [comment]
Really what it means is that we should be using a language that's actually tail recursive and not stunt the recursive expression of naturally recursive algorithms.

**Comment by vontell** [comment]
Yes that would certainly be better

**Comment by tarballs-are-good** [comment]
What about `sys.setrecursionlimit`?

**Comment by tarballs-are-good** [comment]
Closing, due to non-bug. If this pops up again, we can add a note to the docs.
