### ISSUE TITLE
Migrate Grove to python3

### ISSUE THREAD

**Issue by ncrubin** [rigetticomputing/grove#43]

**Comment by waseem18** [comment]
Hi @ncrubin 

I'm interested in this project and would like to work on this task of migrating Grove to Python3.

I'll report my progress as I start working on this.

Thank You.

**Comment by ncrubin** [comment]
Sounds great!

**Comment by waseem18** [comment]
@ncrubin Do I strictly port the code to Python 3 or should the code support both Python 2 and 3?

**Comment by jotterbach** [comment]
@waseem18, thanks for taking on this task! The library should support both versions. Have a look at https://github.com/rigetticomputing/pyquil/pull/66 and https://github.com/rigetticomputing/pyquil/pull/68, where we introduced tox and corresponding python2.7 and python3.6 test automation.

**Comment by waseem18** [comment]
Thanks for the information @ncrubin and @jotterbach . I'll start looking into this. :)

**Comment by jotterbach** [comment]
See https://github.com/rigetticomputing/grove/pull/57

**Comment by jotterbach** [comment]
The above two PRs fix this issue
