### ISSUE TITLE
Readthedocs source code docs don't show up

### ISSUE THREAD

**Issue by joelin0** [rigetticomputing/grove#55]
In each page of documentation for the modules, at the bottom of the page (here, for example: http://grove-docs.readthedocs.io/en/latest/qaoa.html#source-code-docs), only the headings for the Source Code Docs show up, but no code/documentation.

**Comment by dangirsh** [comment]
Issue is this: http://docs.readthedocs.io/en/latest/faq.html#my-project-isn-t-building-with-autodoc

I have a branch with a fix named `bugfix/55/add_pyquil_doc_dep`. Trying to test it on readthedocs now.

**Comment by dangirsh** [comment]
Seems to have worked: http://grove-docs.readthedocs.io/en/pyquil-doc-dep/grover.html#source-code-docs

NB: RTD only picks up new versions if you push a new tag AND trigger a build.
