### ISSUE TITLE
ImportError: No module named utils.utility_programs

### ISSUE THREAD

**Issue by rasa97** [rigetticomputing/grove#91]
When I try to run 
`from grove.amplification.oracles import basis_selector_oracle`

it returns the error:
```
from grove.utils.utility_programs import ControlledProgramBuilder
ImportError: No module named utils.utility_programs
```

After downloading the file from https://pypi.python.org/pypi/quantum-grove/1.2.0 , i find that there is no utils folders inside the grove folder.

**Comment by jotterbach** [comment]
Thanks for flagging @rasa97 . We'll take a look at this!

**Comment by ampolloreno** [comment]
@rasa97 When I install from a source distribution, I don't see this error. When I install from pypi, I do. (As you said)

This should therefore be fixed in the next release. Thank you for the bug report!

**Comment by ogamel** [comment]
I have the same issue and I installed mine using pip. Is there a current workaround before the next release of grove?
Thanks

**Comment by ampolloreno** [comment]
@ogamel One option (the one I've been using) is to clone the repo, and use `pip install -e path/to/grove`.

Sorry for the inconvenience! (We should be releasing a new version soon...)

**Comment by jotterbach** [comment]
@rasa97 @ogamel We just pushed a new release to pypi. This should hopefully address this install bug.

**Comment by jotterbach** [comment]
@ogamel @rasa97 I verified on my MacOSX and Ubuntu16.04 that this works now:

```Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from grove.amplification.oracles import basis_selector_oracle
>>> ```

```Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from grove.amplification.oracles import basis_selector_oracle
>>>```

Closing this one out
