### ISSUE TITLE
Finding the state of the system after Oracle.

### ISSUE THREAD

**Issue by rasa97** [rigetticomputing/grove#97]
Working on Deutsch-Jozsa. I want to find the wavefunction of our system after undergoing the oracle.

```
def dj(oracle, qubits, ancilla):
    p = pq.Program()
    p.inst(X(ancilla), H(ancilla))

    p.inst([H(qubit) for qubit in qubits])
    p += oracle
    print qvm.wavefunction(p)[0]                        #Displaying the wavefunction.
    p.inst([H(qubit) for qubit in qubits])
    return p

deutsch_program = pq.Program()
qubits = [deutsch_program.alloc() for _ in range(n)]
ancilla = deutsch_program.alloc()

unitary_funct = unitary_function(mappings)     #Mappings list is initialised before.
oracle = oracle_function(unitary_funct, qubits, ancilla)
deutsch_program += dj(oracle, qubits, ancilla)  #Changed function to dj()
deutsch_program.out()
```
This is producing `RuntimeError: Can't get the index of an unassigned qubit.` How can I get the wavefunction after the oracle?

**Comment by jotterbach** [comment]
@rasa97 Thanks for the issue report! We just refactored the Deutsch-Josza module significantly. Would you mind looking at it again and see if this is still an issue?

**Comment by rasa97** [comment]
The refactored one works for single qubit. However, when I run the code for 2-qubits, there are errors. For balanced, I get:

The code is `print dj.is_constant(qvm, {'00':'0', '01':'1', '10':'0', '11':'1'})`

```
line 147, in unitary_function
value = int(mappings[bitstring])
KeyError: '0'
```

For constant, I get the error:

```
line 59, in is_constant
     constant = all([bit == 0 for bit in bitstring])
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The code is `print dj.is_constant(qvm, {'00':'0', '01':'0', '10':'0', '11':'0'})`

**Comment by ampolloreno** [comment]
@rasa97 Thank you for the followup! I'm opening up a PR to fix this!

**Comment by rasa97** [comment]
I'm curious to know why the inputs should be represented in a dict. Isn't list enough? Its easier that way, right?

**Comment by jotterbach** [comment]
@rasa97 I agree that a list has less overhead, but it also makes implicit assumptions about ordering. Moreover, the structure of a `dict` highlights the structure of the problem and makes it more apparent. In the end you will have to provide `2**n` inputs, so an additional factor of `2` will not make too much of a difference.

What's your thought on this?

**Comment by rasa97** [comment]
For the sake of convenience, list is better I guess. If the user has an idea about the ordering, it would be easier to just type in the bits. The pattern in which it should be typed can be highlighted in docs.
